#!/usr/bin/env bash
# shellcheck source=./scripts/constants.sh

set -euo pipefail
source ./scripts/constants.sh

usage_intro(){
    echo "leet-problem - custom cli tool for leet code file management"
    echo "Usage: leet-problem [--help]"
    echo "                    <command> [<arguments>]"
    echo "  new     Add a problem, generate files and update readme/meta datas"
    echo "  status  Update a problem status in readme/meta datas"
    echo ""
    [[ $1 -eq 1 ]] && echo "leet-problem <command> --help"
    [[ $1 -eq 1 ]] && echo "  Get detail for specific command use"
    [[ $1 -eq 1 ]] && exit 1
    echo ""
}

usage_new() {
    [[ $1 -eq 1 ]] && echo "leet-problem - custom cli tool for leet code file management"
    echo ""
    echo "Command new"
    echo "Usage:    leet-problem new <leetcode-url> [lang...]"
    echo "Languages: c  cpp  python  csharp  mysql"
    echo ""
    echo "Example: leet-problem new https://leetcode.com/problems/two-sum/ c cpp"
}

usage_status() {
    [[ $1 -eq 1 ]] && echo "leet-problem - custom cli tool for leet code file management"
    echo ""
    echo "Command update"
    echo "Usage:    leet-problem status <slug> <value>"
    echo "Values:"
    for code in $(echo "${!STATUS[@]}" | tr ' ' '\n' | sort -n); do
        echo "  $code — ${STATUS[$code]}"
    done
    echo ""
    echo "Example: leet-problem status insert-delete-getrandom-o1 2"
}

usage_all(){
    usage_intro 0
    usage_new 0
    usage_status 0
}

[[ $# -eq 0 ]] && usage_intro 1
FUNCTION_ARG="$1"
shift

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/scripts" && pwd)"

case "$FUNCTION_ARG" in
        new)
            if [[ $# -lt 2 || $1 = "--help" ]]; then
                usage_new 1
            else
                echo "[leet-problem] Adding new problem"
                "$SCRIPTS_DIR/new_problem.sh" "$@"
            fi
            ;;
        status)
            if [[ $# -lt 2 ||  $1 = "--help" ]]; then
                usage_status 1
            else
                echo "[leet-problem] Updating status"
                "$SCRIPTS_DIR/status_update.sh" "$@"
            fi
            ;;
        --help)
            usage_all
            ;;
        *)
            echo "[leet-problem] Unknown argument, refer to --help"
            exit 1
            ;;
    esac
exit 0