#!/usr/bin/env bash
set -euo pipefail

SLUG="${1:?Usage: gen_makefile.sh <slug>}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROB_DIR="$REPO_ROOT/problems/$SLUG"

[[ -d "$PROB_DIR" ]] || { echo "[gen_makefile] Directory not found: $PROB_DIR" >&2; exit 1; }

MAKEFILE="$PROB_DIR/Makefile"

all_targets=""

add_target() {
    local lang="$1"
    all_targets="$all_targets $lang"
}

emit_c() {
    cat <<'EOF'
build-c:
	gcc -Wall -Wextra -o solution_c solution.c test_solution.c
test-c: build-c
	./solution_c
clean-c:
	rm -f solution_c
EOF
}

emit_cpp() {
    cat <<'EOF'
build-cpp:
	g++ -Wall -Wextra -std=c++17 -o solution_cpp solution.cpp test_solution.cpp
test-cpp: build-cpp
	./solution_cpp
clean-cpp:
	rm -f solution_cpp
EOF
}

emit_python() {
    cat <<'EOF'
build-python:
	python3 -m py_compile solution.py
test-python:
	@if [ -f solution_test.py ]; then python3 -m pytest solution_test.py -v; else python3 -m py_compile solution.py && echo "syntax ok"; fi
clean-python:
EOF
}

emit_csharp() {
    cat <<'EOF'
build-csharp:
	@if command -v dotnet >/dev/null 2>&1; then dotnet build; \
	elif command -v mcs >/dev/null 2>&1; then mcs solution.cs; \
	else echo "No C# compiler found"; exit 1; fi
test-csharp: build-csharp
	@if com
CONTENT_HTML=$(jq -r '.content // ""' "$CACHE_FILE")mand -v dotnet >/dev/null 2>&1; then dotnet test; \
	else echo "Run manually with mono"; fi
clean-csharp:
	rm -f *.exe
EOF
}

emit_mysql() {
    cat <<'EOF'
build-mysql:
	@mysql --help >/dev/null 2>&1 && echo "mysql client present" || (echo "mysql not found"; exit 1)
test-mysql:
	@echo "SQL: run solution.sql manually against a MySQL instance"
clean-mysql:
EOF
}

{
    echo "# Auto-generated by gen_makefile.sh — do not edit manually"
    echo ""

    build_deps=""
    test_deps=""
    clean_deps=""

    [[ -f "$PROB_DIR/solution.c" ]]      && build_deps="$build_deps build-c"   && test_deps="$test_deps test-c"   && clean_deps="$clean_deps clean-c"
    [[ -f "$PROB_DIR/solution.cpp" ]]    && build_deps="$build_deps build-cpp" && test_deps="$test_deps test-cpp" && clean_deps="$clean_deps clean-cpp"
    [[ -f "$PROB_DIR/solution.py" ]]     && build_deps="$build_deps build-python" && test_deps="$test_deps test-python" && clean_deps="$clean_deps clean-python"
    [[ -f "$PROB_DIR/solution.cs" ]]     && build_deps="$build_deps build-csharp" && test_deps="$test_deps test-csharp" && clean_deps="$clean_deps clean-csharp"
    [[ -f "$PROB_DIR/solution.sql" ]]    && build_deps="$build_deps build-mysql" && test_deps="$test_deps test-mysql" && clean_deps="$clean_deps clean-mysql"

    echo ".PHONY: build test clean$build_deps$test_deps$clean_deps"
    echo ""
    echo "build:$build_deps"
    echo ""
    echo "test:$test_deps"
    echo ""
    echo "clean:$clean_deps"
    echo ""

    [[ -f "$PROB_DIR/solution.c" ]]   && emit_c
    [[ -f "$PROB_DIR/solution.cpp" ]] && emit_cpp
    [[ -f "$PROB_DIR/solution.py" ]]  && emit_python
    [[ -f "$PROB_DIR/solution.cs" ]]  && emit_csharp
    [[ -f "$PROB_DIR/solution.sql" ]] && emit_mysql

} > "$MAKEFILE"

echo "[gen_makefile] Written: $MAKEFILE"
